[build]
  command = "npm run netlify"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
