version: 2.1
orbs:
  node: circleci/node@5.1.0
  netlify-cli: netlify/netlify-cli@2.0.0

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - netlify-cli/install
      - netlify-cli/deploy:
          site-id: ${NETLIFY_SITE_ID}
          auth-token: ${NETLIFY_AUTH_TOKEN}
          build-command: echo "Already built"
          path: .output/public
          prod-if-successful: true

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
